{% set name = "google-cloud-monitoring" %}
{% set version = "0.29.0" %}
{% set sha256 = "9e384c235b4f33c733bf55c4b8cbc41ee91ab6f79d36b7189d5b8eb11e865e31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - google-cloud-core >=0.24.0,<0.25dev

test:
  imports:
    - google.cloud.monitoring

about:
  home: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/monitoring
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python Client for Google Stackdriver Monitoring'
  description: Python idiomatic client for Google Stackdriver Monitoring
  doc_url: https://googlecloudplatform.github.io/google-cloud-python/stable/monitoring-usage.html
  dev_url: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/monitoring

extra:
  recipe-maintainers:
    - parthea
