{% set name = "google-cloud-monitoring" %}
{% set version = "0.36.0" %}
{% set sha256 = "ff69ca820fcbbc7881745e5e225e4a5751f8fd6a7efa5c7082fcfab684103df3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python
    - pip

  run:
    - python >=3.5
    - google-api-core-grpc >=1.14.0,<2.0.0dev

test:
  imports:
    - google.cloud.monitoring
    - google.cloud.monitoring_v3

about:
  home: https://github.com/googleapis/python-monitoring
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python Client for Stackdriver Monitoring API'
  description: Python idiomatic client for Google Stackdriver Monitoring
  doc_url: https://googleapis.dev/python/monitoring/latest/index.html

extra:
  recipe-maintainers:
    - parthea
