{% set name = "google-cloud-monitoring" %}
{% set version = "2.22.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9fc22dac48d14dd1c7fb83ee4a54f7a57bf9852ee6b5c9dca9e3bb093b04c7ee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - google-api-core >=1.34.1,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0dev,!=2.24.0,!=2.25.0
    - proto-plus >=1.22.3,<2.0.0dev
    - protobuf >=3.20.2,<6.0.0dev,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - google.cloud.monitoring
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-monitoring
  summary: Google Cloud Monitoring API client library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: Python idiomatic client for Google Stackdriver Monitoring
  doc_url: https://googleapis.dev/python/monitoring/latest/index.html

extra:
  recipe-maintainers:
    - parthea
    - xylar
