{% set name = "google-cloud-monitoring" %}
{% set version = "2.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 78b77c9478721a32414da3733fc6a6cd66b72f26808b1ce3fba129454d89d1b8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-api-core-grpc >=1.32.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*
    - proto-plus >=1.15.0,<2.0.0dev
    - protobuf >=3.19.0,<4.0.0dev

test:
  imports:
    - google.cloud.monitoring
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-monitoring
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python Client for Stackdriver Monitoring API
  description: Python idiomatic client for Google Stackdriver Monitoring
  doc_url: https://googleapis.dev/python/monitoring/latest/index.html

extra:
  recipe-maintainers:
    - parthea
    - xylar
